version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/radius-plugin # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.2-node

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run:
          name: build and test plugins
          command: cd keycloak-plugins && mvn clean install && mvn coveralls:report -Dcoveralls=false -DrepoToken=$COVERALLS_TOKEN
      - run:
          name: install hotspot ui
          command: cd hotspot/source && npm i
      - run:
          name: build hotspot ui
          command: cd hotspot/source && npm run lint
      - run:
          name: build hotspot ui
          command: cd hotspot/source && npm run build
